title: Atharva Bhagwat
markdown: kramdown
url: "https://atharva-bhagwat.github.io"
baseurl: ""
# logo: "images/logo/nohello.png"
logo: "https://github.com/simonhearne/nohello.club/blob/master/images/nohello_640_tr_w.png"

# for atom feed
author:
  name: Atharva Bhagwat
  email: atharva.bhagwat42@gmail.com

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
