title: Atharva Bhagwat
markdown: kramdown
url: "https://atharva-bhagwat.github.io"
baseurl: ""

# for atom feed
author:
  name: Atharva Bhagwat
  email: atharva.bhagwat42@gmail.com

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

# TODO: post ideas: cv projects, you can add theory code etc. solve leetcode solutions for the 14 day challenge.
#                   find ml topics to talk about (p-value, residual deviance, null deviance meaning??), analysis of all algorithms?